In [1]:
import numpy as np
import pandas as pd 
import wget
import os

url_owid = ['https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv']

path_url = r'C:\Users\Acer\Documents\Belajar Data Science\Source Code Project\Covid19-Report-Indonesia\Dataset\Owid'

for url in url_owid:
    filename= path_url + '/' + os.path.basename(url)
    if os.path.exists(filename):
        os.remove(filename) # if exist, remove it directly
    wget.download(url, out=path_url)

100% [........................................................................] 24127712 / 24127712

In [2]:
cov19_data_owid = pd.read_csv(r'C:\Users\Acer\Documents\Belajar Data Science\Source Code Project\Covid19-Report-Indonesia\Dataset\Owid\owid-covid-data.csv')
cov19_data_owid.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

In [3]:
cov19_id_owid = cov19_data_owid[cov19_data_owid['location'] == 'Indonesia']
cov19_id_owid.tail()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
39201,IDN,Asia,Indonesia,2021-05-27,1797499.0,6278.0,5514.429,49907.0,136.0,145.714,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
39202,IDN,Asia,Indonesia,2021-05-28,1803361.0,5862.0,5531.000,50100.0,193.0,146.714,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
39203,IDN,Asia,Indonesia,2021-05-29,1809926.0,6565.0,5712.286,50262.0,162.0,151.000,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
39204,IDN,Asia,Indonesia,2021-05-30,1816041.0,6115.0,5831.571,50404.0,142.0,153.714,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
39205,IDN,Asia,Indonesia,2021-05-31,1821703.0,5662.0,5796.571,50578.0,174.0,160.429,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718

In [4]:
print(cov19_id_owid.info())
print(cov19_id_owid.isna().sum())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 456 entries, 38750 to 39205
Data columns (total 59 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   iso_code                               456 non-null    object
 1   continent                              456 non-null    object
 2   location                               456 non-null    object
 3   date                                   456 non-null    object
 4   total_cases                            456 non-null    float64
 5   new_cases                              456 non-null    float64
 6   new_cases_smoothed                     451 non-null    float64
 7   total_deaths                           447 non-null    float64
 8   new_deaths                             447 non-null    float64
 9   new_deaths_smoothed                    451 non-null    float64
 10  total_cases_per_million                456 non-null    float64
 11  new_cases_per_million                  456 non-null    float64
 12  new_cases_smoothed_per_million         451 non-null    float64
 13  total_deaths_per_million               447 non-null    float64
 14  new_deaths_per_million                 447 non-null    float64
 15  new_deaths_smoothed_per_million        451 non-null    float64
 16  reproduction_rate                      440 non-null    float64
 17  icu_patients                           0 non-null      float64
 18  icu_patients_per_million               0 non-null      float64
 19  hosp_patients                          0 non-null      float64
 20  hosp_patients_per_million              0 non-null      float64
 21  weekly_icu_admissions                  0 non-null      float64
 22  weekly_icu_admissions_per_million      0 non-null      float64
 23  weekly_hosp_admissions                 0 non-null      float64
 24  weekly_hosp_admissions_per_million     0 non-null      float64
 25  new_tests                              335 non-null    float64
 26  total_tests                            372 non-null    float64
 27  total_tests_per_thousand               372 non-null    float64
 28  new_tests_per_thousand                 335 non-null    float64
 29  new_tests_smoothed                     431 non-null    float64
 30  new_tests_smoothed_per_thousand        431 non-null    float64
 31  positive_rate                          431 non-null    float64
 32  tests_per_case                         431 non-null    float64
 33  tests_units                            438 non-null    object
 34  total_vaccinations                     96 non-null     float64
 35  people_vaccinated                      96 non-null     float64
 36  people_fully_vaccinated                90 non-null     float64
 37  new_vaccinations                       66 non-null     float64
 38  new_vaccinations_smoothed              138 non-null    float64
 39  total_vaccinations_per_hundred         96 non-null     float64
 40  people_vaccinated_per_hundred          96 non-null     float64
 41  people_fully_vaccinated_per_hundred    90 non-null     float64
 42  new_vaccinations_smoothed_per_million  138 non-null    float64
 43  stringency_index                       456 non-null    float64
 44  population                             456 non-null    float64
 45  population_density                     456 non-null    float64
 46  median_age                             456 non-null    float64
 47  aged_65_older                          456 non-null    float64
 48  aged_70_older                          456 non-null    float64
 49  gdp_per_capita                         456 non-null    float64
 50  extreme_poverty                        456 non-null    float64
 51  cardiovasc_death_rate                  456 non-null    float64
 52  diabetes_prevalence                    456 non-null    float64
 53  female_smokers                         456 non-null    float64
 54  male_smokers                           456 non-null    float64
 55  handwashing_facilities                 456 non-null    float64
 56  hospital_beds_per_thousand             456 non-null    float64
 57  life_expectancy                        456 non-null    float64
 58  human_development_index                456 non-null    float64
dtypes: float64(54), object(5)
memory usage: 213.8+ KB
None
iso_code                                   0
continent                                  0
location                                   0
date                                       0
total_cases                                0
new_cases                                  0
new_cases_smoothed                         5
total_deaths                               9
new_deaths                                 9
new_deaths_smoothed                        5
total_cases_per_million                    0
new_cases_per_million                      0
new_cases_smoothed_per_million             5
total_deaths_per_million                   9
new_deaths_per_million                     9
new_deaths_smoothed_per_million            5
reproduction_rate                         16
icu_patients                             456
icu_patients_per_million                 456
hosp_patients                            456
hosp_patients_per_million                456
weekly_icu_admissions                    456
weekly_icu_admissions_per_million        456
weekly_hosp_admissions                   456
weekly_hosp_admissions_per_million       456
new_tests                                121
total_tests                               84
total_tests_per_thousand                  84
new_tests_per_thousand                   121
new_tests_smoothed                        25
new_tests_smoothed_per_thousand           25
positive_rate                             25
tests_per_case                            25
tests_units                               18
total_vaccinations                       360
people_vaccinated                        360
people_fully_vaccinated                  366
new_vaccinations                         390
new_vaccinations_smoothed                318
total_vaccinations_per_hundred           360
people_vaccinated_per_hundred            360
people_fully_vaccinated_per_hundred      366
new_vaccinations_smoothed_per_million    318
stringency_index                           0
population                                 0
population_density                         0
median_age                                 0
aged_65_older                              0
aged_70_older                              0
gdp_per_capita                             0
extreme_poverty                            0
cardiovasc_death_rate                      0
diabetes_prevalence                        0
female_smokers                             0
male_smokers                               0
handwashing_facilities                     0
hospital_beds_per_thousand                 0
life_expectancy                            0
human_development_index                    0
dtype: int64

In [5]:
# Handle missing value:
## first using ffill method
cov19_id_owid = cov19_id_owid.fillna(method='ffill')

In [6]:
## second, replace null values with 0
cov19_id_owid = cov19_id_owid.fillna(0)

In [7]:
cov19_id_owid

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
38750,IDN,Asia,Indonesia,2020-03-02,2.0,2.0,0.000,0.0,0.0,0.000,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
38751,IDN,Asia,Indonesia,2020-03-03,2.0,0.0,0.000,0.0,0.0,0.000,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
38752,IDN,Asia,Indonesia,2020-03-04,2.0,0.0,0.000,0.0,0.0,0.000,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
38753,IDN,Asia,Indonesia,2020-03-05,2.0,0.0,0.000,0.0,0.0,0.000,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
38754,IDN,Asia,Indonesia,2020-03-06,4.0,2.0,0.000,0.0,0.0,0.000,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39201,IDN,Asia,Indonesia,2021-05-27,1797499.0,6278.0,5514.429,49907.0,136.0,145.714,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
39202,IDN,Asia,Indonesia,2021-05-28,1803361.0,5862.0,5531.000,50100.0,193.0,146.714,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
39203,IDN,Asia,Indonesia,2021-05-29,1809926.0,6565.0,5712.286,50262.0,162.0,151.000,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
39204,IDN,Asia,Indonesia,2021-05-30,1816041.0,6115.0,5831.571,50404.0,142.0,153.714,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718
39205,IDN,Asia,Indonesia,2021-05-31,1821703.0,5662.0,5796.571,50578.0,174.0,160.429,...,11188.744,5.7,342.864,6.32,2.8,76.1,64.204,1.04,71.72,0.718

In [8]:
path1=r'C:\Users\Acer\Documents\Belajar Data Science\Source Code Project\Covid19-Report-Indonesia\Dataset\Owid' 
cov19_id_owid = cov19_id_owid.set_index(keys='iso_code')
cov19_id_owid.to_csv(os.path.join(path1, r'cov19_id_owid.csv'))